version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    cooldown:
      default-days: 7
    schedule:
      interval: 'daily'
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: "github-actions"
    directory: "/"
    cooldown:
      default-days: 7
    schedule:
      interval: "daily"
